config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => "/sidekiq"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "save_fcm_token", to: "fcm_tokens#create"
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "reminders#index"
  get "request_demo" => "pages#request_demo"
  patch "reminders/:id/toggle_complete", to: "reminders#toggle_complete", as: :toggle_complete
  resources :reminders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fcm_token.rb
class FcmToken < ApplicationRecord
  belongs_to :user
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reminders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attribute :fcm_token, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, if: :devise_controller?
  private

  def authenticate_user!
    unless user_signed_in? || allowed_pages.include?(action_name)
      redirect_to request_demo_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :discord_id ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :discord_id ])
  end

  def allowed_pages
    %w[request_demo new create]
  end
end

app/controllers/fcm_tokens_controller.rb
class FcmTokensController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :create ]
  before_action :authenticate_user!

  def create
    user = current_user
    token = params[:fcm_token]

    if user.update(fcm_token: token)
      render json: { message: "Token successfully stored" }, status: :ok
    else
      render json: { error: "Failed to store token" }, status: :unprocessable_entity
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def request_demo
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  def show
    @reminder = Reminder.find(params[:id])
  end

  def index
    @reminders = current_user.reminders.all
  end

  def new
    @reminder = current_user.reminders.build
  end

  def create
    @reminder = current_user.reminders.build(reminder_params)
    if @reminder.save
      # DiscordBotService.new.notify_new_reminder(@reminder)
      # CheckerJob.perform_at(@reminder.strike - 60.seconds, @reminder.id)
      redirect_to root_path
    end
  end

  def edit
    @reminder = Reminder.find(params[:id])
  end

  def update
    @reminder = Reminder.find(params[:id])

    if @reminder.update(reminder_params)
      redirect_to @reminder
    end
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy

    redirect_to root_path, status: :see_other
  end

  def toggle_complete
    @reminder = Reminder.find(params[:id])
    @reminder.update(complete: !@reminder.complete, counter: @reminder.counter + 1)
    redirect_to root_path
  end



  private

  def send_push_notification(reminder)
    fcm_token = current_user.fcm_token
    Rails.logger.info("FCM token: #{fcm_token.inspect}")
    return unless fcm_token

    fcm = FCM.new(ENV["FCM_SERVER_KEY"])
    options = {
      notification: {
        title: "New Reminder Created",
        body: "Reminder: #{reminder.name}",
        icon: "/path/to/icon.png",
        click_action: reminder_url(reminder)
      }
    }

    response = fcm.send([ fcm_token ], options)
    Rails.logger.info("FCM response: #{response[:status_code]} - #{response[:body]}")
    if response[:status_code] != 200
      Rails.logger.error("FCM error: #{response[:body]}")
    end
  end

  def reminder_params
    params.require(:reminder).permit(:name, :strike, :description, :complete, :counter, :active, :repeat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ubiquity Theo Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>



  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/pages/landing.html.erb
<%= stylesheet_link_tag "landing", "data-turbo-track": "reload" %>
<div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
  <div id="content" class="d-flex flex-column justify-content-center align-items-center w-100 h-100">
    <h1 class="fw-light text-white m-0">Ubiquity Project</h1>
    <br>
    <h3 class="fw-light text-white m-0">Request a demo</h3>
    <div class="btn-group my-5">
      <a href="https://codepen.io/P1N2O/full/pyBNzX" class="btn btn-outline-light">help@ubiquityproject.co.uk<i class="fas fa-expand ms-2"></i></a>
    </div>
    <h5 class="fw-light text-white m-0">Prepare for what’s ahead, be present in the now, and remember what’s been.</h5>

  </div>
</div>

app/views/pages/request_demo.erb
<%= stylesheet_link_tag "request_demo", "data-turbo-track": "reload" %>
<div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
  <div id="content" class="d-flex flex-column justify-content-center align-items-center w-100 h-100">
    <h1 class="fw-light text-white m-0">Ubiquity Project</h1>
    <br>
    <h3 class="fw-light text-white m-0">Request a demo</h3>
    <div class="btn-group my-5">
      <p id="email" style="color: white; border-bottom: solid;"> help@ubiquityproject.co.uk </p>
    </div>
    <h5 class="fw-light text-white m-0">Prepare for what's ahead</h5>
    <h5 class="fw-light text-white m-0">Be present in the now</h5>
    <h5 class="fw-light text-white m-0">and remember what's been</h5>

  </div>
</div>

app/views/reminders/edit.html.erb
<h1>Edit Reminder!</h1>

<%= form_with model: @reminder do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/index.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<div class="container-fluid">
  <div id="left-cont">
    <div id="top-left">
    </div>
    <div id="l-times">
    <% @reminders.each do |reminder| %>
      <% time = reminder.strike.strftime("%H:%M")%>
      <%if reminder.complete == false%>
      <div class="time-box">
        <p><%= time %></p>
      </div>
      <%end%>
      <%end%>
    </div>
  </div>
  <div id="mid-cont">
  <div id="menu">
      Menu
    </div>
  <div class="reminder-cont">

    <% @reminders.each do |reminder| %>

      <%if reminder.complete == false%>

      <div class="reminder">
        <div class="name"><%= reminder.name %></div>



        <div class="delete">
          <%= form_with url: toggle_complete_path(reminder), method: :patch, local: true do |form| %>
              <%= form.hidden_field :complete, value: !reminder.complete %>
              <%= form.submit "", style: "width: 50%;" %>
            <% end %>
         <!-- <# link_to "x", reminder_path(reminder), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }  -->

        </div>
      </div>
      <%end%>
      <% end %>
  </div>
  </div>

  <div class="control">
    <div id="top-right">

    </div>
    <div class="right-bar" id="x-1">

    </div>
    <div class="right-bar" id="x-2">

    </div>
    <div class="right-bar" id="x-3">

    </div>
    <div class="right-bar" id="x-4">

    </div>
    <div class="right-bar" id="x-5">

    </div>
    <div class="right-bar" id="x-6">
      <i class="bi bi-person-circle"></i>
    </div>
    <div class="right-bar" id="x-7">

      <i class="bi bi-vector-pen"></i>
    </div>
    <div class="right-bar" id="x-8">
    <%= link_to new_reminder_path do %>
          <i class="bi bi-plus-circle-fill"></i>
        <% end %>

    </div>

  </div>
</div>

app/views/reminders/new.html.erb
<%= stylesheet_link_tag "new_reminder", "data-turbo-track": "reload" %>
<div class="container-fluid">
  <div id="left-cont">
    <div id="top-left">
    </div>
    <div class="time-box">
        <p id="time-target"></p>
      </div>
  </div>
  <div id="mid-cont">
    <input id="name-input" type="text" style="position: absolute; opacity: 0; height: 0;">
  <div id="menu">
      Menu
    </div>
  <div class="reminder-cont">
    <div class="reminder" id="name-target">
        <div class="name">
          <p id="name-target"></p>
        </div>
      </div>
      <div class="reminder">
        <%= form_with model: @reminder do |form| %>
        <div class="name"><%=form.text_field :strike%></div>
        <div class="desc"><%=form.text_field :name%></div>


        <div class="delete"><%=form.text_field :description%><%=form.submit %>


        </div>
        <%end%>
      </div>


      <div class=reminder style="visibility: hidden" >
        <div class="name"></div>
        <div class="desc"></div>
        <div class="delete"></div>
      </div>
      <div class=reminder style="visibility: hidden" >
        <div class="name"></div>
        <div class="desc"></div>
        <div class="delete"></div>
      </div>
      <div class="control-pad" id="control-pad-time" style="display:block;">
        <div id="row-1">
          <i class="bi bi-7-square" style="font-size: 5vh;"></i>
          <i class="bi bi-8-square" style="font-size: 5vh;"></i>
          <i class="bi bi-9-square" style="font-size: 5vh;"></i>
        </div>
        <div id="row-2">
          <i class="bi bi-4-square" style="font-size: 5vh;"></i>
          <i class="bi bi-5-square" style="font-size: 5vh;"></i>
          <i class="bi bi-6-square" style="font-size: 5vh;"></i>
        </div>
        <div id="row-3">
          <i class="bi bi-1-square" style="font-size: 5vh;"></i>
          <i class="bi bi-2-square" style="font-size: 5vh;"></i>
          <i class="bi bi-3-square" style="font-size: 5vh;"></i>
        </div>
      </div>
      <div class="control-pad" id="control-pad-name" style="display: none">
      </div>
      <div class="control-pad" id="control-pad-platforms" style="display: none">
      </div>



  </div>
  </div>

  <div class="control">
    <div id="x-1">
    <i class="bi bi-app" style="font-size: 5vh;"></i>
    </div>
    <div id="x-2">
      <i class="bi bi-gear" style="font-size: 5vh;"></i>
    </div>
    <div id="x-3">
    <i class="bi bi-app" style="font-size: 5vh;"></i>
    </div>
    <div id="x-4">
    <i class="bi bi-pencil-square" style="font-size: 5.5vh;"></i>
    </div>
    <div id="x-5">
    <%= link_to new_reminder_path do %>
          <i class="bi bi-plus-square" style="font-size: 5vh;"></i></i>
        <% end %>
    </div>
    <div id="x-6">
    <i class="bi bi-clock-fill" style="font-size: 5vh;"></i>
    </div>
    <div id="x-7">
    <i class="bi bi-alphabet-uppercase"style="font-size: 5vh;"></i>
    </div>
    <div id="x-8">
    <i class="bi bi-bell-fill" style="font-size: 5vh;"></i>
    </div>
    <div id="x-9">
    <i class="bi bi-app" style="font-size: 5vh;"></i>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
  // Get the element with the class 'bi bi-alphabet-uppercase'
  const alphabetButton = document.querySelector(".bi.bi-alphabet-uppercase");

  // Get the element with the id 'control-pad-time'
  const controlPadTime = document.getElementById("control-pad-time");

  // Add a click event listener to the alphabet button
  if (alphabetButton && controlPadTime) {
    alphabetButton.addEventListener("click", function() {
      // Change the style of 'control-pad-time' to 'display: none'
      controlPadTime.style.display = "none";

      // Get the hidden input field
      const input = document.getElementById('name-input');

      // Focus on input to open keyboard
      input.focus();

      // Listen for input events to update the target paragraph in real time
      input.addEventListener('input', () => {
        const target = document.getElementById('name-target');
        target.textContent = input.value; // Update target with input's value
      });
    });
  }
});
</script>

app/views/reminders/show.html.erb
<h1>Name</h1>
<h2><%=@reminder.name%><h2>
<h1>Description</h1>
<%=@reminder.description%>
<%= link_to "Destroy", reminder_path(@reminder), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"}%>